apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-uploader-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-uploader
  template:
    metadata:
      labels:
        app: secure-uploader
    spec:
      initContainers:
        - name: setup-env
          image: praveenmtsget/file-uploader-app:beta-1749559567
          command: ['sh', '-c']
          args:
            - >
              echo "Starting initContainer: copying static files..." &&
              cp -r /app/. /usr/share/nginx/html/ &&
              echo "Static files copied." &&
              echo "Creating env.js file..." &&
              echo "const SUPABASE_URL = '${SUPABASE_URL}';" > /usr/share/nginx/html/env.js &&
              echo "const SUPABASE_ANON_KEY = '${SUPABASE_ANON_KEY}';" >> /usr/share/nginx/html/env.js &&
              echo "env.js file created with SUPABASE_URL and SUPABASE_ANON_KEY."
          envFrom:
            - configMapRef:
                name: supabase-config
          volumeMounts:
            - name: web-root
              mountPath: /usr/share/nginx/html
      
      containers:
      - name: web
        image: praveenmtsget/file-uploader-app:beta-1749559567
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-root
          mountPath: /usr/share/nginx/html

      volumes:
      - name: web-root
        emptyDir: {}