apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-uploader-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-uploader
  template:
    metadata:
      labels:
        app: secure-uploader
    spec:
      initContainers:
      - name: setup-env
        # We need the real image here to access the /app directory
        image: praveenmtsget/file-uploader-app:beta-1749554793 # <-- Use your main app image
        command: ['sh', '-c']
        args:
          - >
            # Step 1: Copy static files from the staging area (/app) to the shared volume
            cp -r /app/. /usr/share/nginx/html/ &&
            # Step 2: Create the env.js file in the shared volume
            echo "const SUPABASE_URL = '${SUPABASE_URL}';" > /usr/share/nginx/html/env.js &&
            echo "const SUPABASE_ANON_KEY = '${SUPABASE_ANON_KEY}';" >> /usr/share/nginx/html/env.js
        envFrom:
          - configMapRef:
              name: supabase-config
        volumeMounts:
        - name: web-root
          mountPath: /usr/share/nginx/html
      
      containers:
      - name: web
        image: praveenmtsget/file-uploader-app:beta-1749554793
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-root
          mountPath: /usr/share/nginx/html

      volumes:
      - name: web-root
        emptyDir: {}