name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set VERSION variable
      id: version_step
      run: echo "VERSION=beta-$(date +%s)" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/file-uploader-app:${VERSION} .

    - name: Tag image as latest
      run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/file-uploader-app:${VERSION} ${{ secrets.DOCKERHUB_USERNAME }}/file-uploader-app:latest

    - name: Push the Docker image (versioned)
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/file-uploader-app:${VERSION}

    - name: Push the Docker image (latest)
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/file-uploader-app:latest
